### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by YuanYuanOwO** [Ghost-chu/QuickShop-Hikari-Documents#24]
page should be update:
- [ ] ItemMatcher 
- [x] Licenses
- [ ] Privacy

other:

- [ ] Added compat-voidchest page
- [ ] Added Recommended MySQL version and Official supported lowest MySQL version to database page
- [ ] https://www.prettier.cn/

**Comment by creatorfromhell** [comment]
Checked off ItemMatcher, Privacy and compat-voidchest since addressed in https://github.com/QuickShop-Community/QuickShop-Hikari-Documents/pull/49
